"""dates of user  login and register

Revision ID: 870d40ff5b35
Revises: 4933d91427d9
Create Date: 2026-01-12 00:36:45.148533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870d40ff5b35'
down_revision: Union[str, Sequence[str], None] = '4933d91427d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'country_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'country', ['country_name'])
    op.alter_column('feedback', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('feedback', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'feedback', 'user', ['user'], ['id'])
    op.create_foreign_key(None, 'feedback', 'film', ['film'], ['id'])
    op.alter_column('film', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('film', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('film', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film', 'poster',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('film', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('film', 'rating',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film', 'added_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_column('film', 'genre')
    op.alter_column('genre', 'genre',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('genre_film', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('genre_film', 'genre_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('genre_film', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'genre_film', 'film', ['film_id'], ['id'])
    op.create_foreign_key(None, 'genre_film', 'genre', ['genre_id'], ['genre'])
    op.add_column('user', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.Date(), nullable=True))
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('user', 'login',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('user', 'photo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user', 'additional_info',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user', 'birth_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'user', ['login'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'birth_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'additional_info',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'photo',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'login',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'last_login')
    op.drop_constraint(None, 'genre_film', type_='foreignkey')
    op.drop_constraint(None, 'genre_film', type_='foreignkey')
    op.alter_column('genre_film', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genre_film', 'genre_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('genre_film', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genre', 'genre',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)
    op.add_column('film', sa.Column('genre', sa.TEXT(), nullable=True))
    op.alter_column('film', 'country',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('film', 'added_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film', 'rating',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film', 'poster',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film', 'name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('film', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.alter_column('feedback', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('feedback', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'country', type_='unique')
    op.alter_column('country', 'country_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
